#n=input('valor de n')
#print(n.isnumeric())
#n=input('valor de n')
#print(n.isalpha())
#n1=int(input('Valor de n1'))
#n2=int(input('Valor de n2'))
#s= n1+n2
#print('A soma entre {} e {} vale {}'.format(n1,n2,s))
x=input('Digite Algo:')
print('O tipo primitivo desse valor é', type(x))
print('Só tem espaço?', x.isspace())
print('É um número?' , x.isnumeric())
print('É alfabético?', x.isalpha())
print('É alfanúmerico?', x.isalnum())
print('Está em maiúsculo?', x.isupper())
print('Está em minúsculo?',x.islower())
print('Está capitalizada?', x.istitle())
